---
name: Eduardo 
surname: Lima
position: "Integration Analyst"
phone: +55 19 11111 1111
address: "Campinas-SP, Brazil"
email: "lima.vaz.eduardo@gmail.com"
linkedin: eduardo1lima
headcolor: 000080 # Navy blue
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(tidyverse)

source("../r/data.R")
```



# About:
```
I have been learning about software development projects since I finished college.  
  I have seen many technologies coming and going. 
  Many programming languages glowing and fading away.  
  Many management approaches fighting to be number one.  

What I have learned so far?  
  People create successful projects, not tools,  
  Successful projects are defined by the customer,  
  People should be the priority,  
  Continuous Improvement is the only way to go,
  Communication plays a major role in achieving the objectives.  
```

# Qualifications:
```{r qualifications}
qualific %>% 
  detailed_entries(why = item)

```



# Education:

```{r education}
education %>% 
  detailed_entries(what = subject,
                   when = year,
                   with = institute)
```


# Courses:
```{r courses}
courses %>% 
  detailed_entries(what = name,
                   when = year,
                   with = school,
                    .protect = FALSE)

```


\pagebreak

# Experience:
```{r experience}
experience %>% 
  detailed_entries(what = company,
                   when = date,
                   where = job,
                   why = desc
                   )

```

\pagebreak

# Certifications:
```{r certifications}
cert %>% detailed_entries(what = name,
                          when = date,
                          why = detail,
                          .protect = FALSE)

```




# Volunteer:
```{r volunteer}
volunteer %>% 
  detailed_entries(
    what = name,
    when = date,
    why = description,
    .protect = FALSE
  )

```



# Articles:
```{r articles}
articles %>% 
  detailed_entries(
    what = description,
    when = date,
    where = name,
    .protect = FALSE
    )

```

